ext {
    extName = 'Tomato'
    extClass = '.Tomato'
    extVersionCode = 5
    isNsfw = false
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation("com.github.hCaptcha.hcaptcha-android-sdk:sdk:5.0.1") {
        exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib"
        exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk7"
        exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk8"
    }
    implementation("androidx.fragment:fragment-ktx:1.8.9")
}

configurations.configureEach {
    exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk7"
    exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk8"
}
